### ISSUE TITLE
Project does not build, unit tests fail with `Cannot create JDBC driver of class '' for connect URL ''`

### ISSUE THREAD

**Issue by lutzhorn** [Alfresco/alfresco-remote-api#194]
This project is not buildable using a simple `mvn package` after a clean clone of the `alfresco-remote-api-7.35` tag which is part of the 201901 GA version.

Many unit tests fail like this:

```
...
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialect': FactoryBean threw exception on object creation; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL ''
        at org.alfresco.repo.web.scripts.upload.UploadWebScriptTest.setUp(UploadWebScriptTest.java:97)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialect': FactoryBean threw exception on object creation; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL ''
        at org.alfresco.repo.web.scripts.upload.UploadWebScriptTest.setUp(UploadWebScriptTest.java:97)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL ''
        at org.alfresco.repo.web.scripts.upload.UploadWebScriptTest.setUp(UploadWebScriptTest.java:97)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL ''
        at org.alfresco.repo.web.scripts.upload.UploadWebScriptTest.setUp(UploadWebScriptTest.java:97)
Caused by: java.sql.SQLException: No suitable driver
        at org.alfresco.repo.web.scripts.upload.UploadWebScriptTest.setUp(UploadWebScriptTest.java:97)
...
```

The interesting line is

```
Cannot create JDBC driver of class '' for connect URL ''
```

which indicates that some database setup is necessary before the project can be build.

* What database setup is required?
* How to tell Maven about the database setup and necessary connection properties?

**Comment by lutzhorn** [comment]
The unit tests require an empty PostgreSQL database.

```bash
$ createdb alfresco-6
$ mvn clean test \
  -Ddb.driver=org.postgresql.Driver \
  -Ddb.name=alfresco-6 \
  -Ddb.url=jdbc:postgresql:alfresco-6 \
  -Ddb.username=lutz \
  -Ddb.password=lutz
```

Using an empty database and the above Maven settings, the build hangs. See #195.
